site_name: Grafos e Redes de Trasmissão

nav: 
    - Problema: index.md
    - grafos: grafos.md
    - Redes: Redes.md
    - Centralidades: Centralidades.md
    - Desenvolvimento: desenvolvimento.md
    - Execução: execucao.md
    - Conclusão: Conclusao.md

theme: readthedocs